'use client'

// Note: @lunagraph/editor/styles.css is imported in layout.tsx BEFORE globals.css
// This ensures Tailwind utilities have higher priority than editor base styles
import { LunagraphEditor, LUCIDE_PROPS_SCHEMA } from "@lunagraph/editor";
import * as lunagraph from '../../.lunagraph/components';
// Import snapshots - generated by dev-server when editing components
import { snapshots, internalComponents } from '../../.lunagraph/snapshots';
// Import Lucide icons
import * as LucideIcons from "lucide-react";

export default function Editor() {
  return (
    <LunagraphEditor
      {...lunagraph}
      components={{ ...lunagraph.components, ...internalComponents }}
      snapshots={snapshots}
      iconLibraries={{
        "lucide-react": {
          icons: LucideIcons,
          displayName: "Lucide",
          defaultProps: { size: 24 },
          propsSchema: LUCIDE_PROPS_SCHEMA,
        }
      }}
    />
  )
}
